name: consulin_mobile_dev
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.11.1

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  http: ^1.6.0
  google_fonts: ^8.0.2
  table_calendar: ^3.2.0
  multi_dropdown: ^3.1.1
  file_picker: ^10.3.10
  fluttertoast: ^9.0.0
  syncfusion_flutter_charts: ^32.2.8
  flutter_svg: ^2.2.3
  flutter_dotenv: ^6.0.0
  loading_animation_widget: ^1.3.0
  stream_chat_flutter: ^9.23.0
  intl: ^0.20.2
  jitsi_meet_flutter_sdk: ^11.6.0
  flutter_native_splash: ^2.4.7
  speech_to_text: ^7.4.0

dev_dependencies:
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
